name: fork_sudoku_dart
description: sudoku_dart is open-source sudoku solver and puzzle generator library with `dart`
version: 0.0.1
homepage: https://github.com/Brilberry/fork-sudoku-dart

environment:
  sdk: ">=3.0.0 <4.0.0"
dev_dependencies:
  test: ^1.22.2

